name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Deploy to VM instance
        run: |
          gcloud compute ssh --zone "${{ secrets.GCP_ZONE }}" "${{ secrets.GCP_INSTANCE }}" \
            --command "cd /home/nikita_zhmak8872/telegram-ai221-sentinel && \
                    git config --global --add safe.directory /home/nikita_zhmak8872/telegram-ai221-sentinel && \
                    git pull && \
                    cd /home/nikita_zhmak8872/telegram-ai221-sentinel/src/bot/ && poetry install && \
                    sudo systemctl restart telegram-bot"